server:
  port: 8081
  tomcat:
    threads:
      max: 300
      min-spare: 30

spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      connection-timeout: 10000
      max-lifetime: 30000
      idle-timeout: 10000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

custom:
  kafka:
    topic:
      order-completed: order.completed.v1
      coupon-issue-request: coupon.issue.request.v1
    consumer:
      group-id:
        order-data-platform: order-data-platform-consumer
        coupon-processor: coupon-issue-processor

---

spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
    hikari:
      maximum-pool-size: 30
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      client-id: hhplus-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 5
      buffer-memory: 67108864
      batch-size: 32768
      linger-ms: 5
      max-block-ms: 5000
    consumer:
      group-id: order-data-platform-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        enable-auto-commit: false
    listener:
      concurrency: 3
      ack-mode: manual

  data:
    redis:
      host: redis
      port: 6379

redisson:
  address: redis://redis:6379

---

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

test:
  kafka:
    groupId: test-group-${random.uuid}
